# Site settings
title: MrbHub
longtitle: MrbHub (blog by Quanzhi Bi)
email: cskksdfklpz@gmail.com
description: MrbHub — Mr. B's blog about math, machine learning, programming and data science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cskksdfklpz.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: cskksdfklpz
# Build settings
markdown: kramdown
